export default {
  Setting: 'Setting',
  EmailAddress: 'Email Address',
  Password: 'Password',
  LogIn: 'Log In',
  Account: `Don't have an account?`,
  Register: 'Register',
  ConfirmPassword: 'Confirm Password',
  HaveAccount: 'Already have an account?',
  LoginSuccessText: 'Login Successful!',
  RequestText: 'Please fill the input field!',
  RegisterSuccessfulText: 'Register Successful!',
  SamePasswordText: 'Password & Confirm password must be the same!',
  ErrorText: 'Email or Password incorrect!',
  LogOut: 'Log out',
  Home: 'Home',
  Profile: 'Profile',
  Terms: 'Terms & Conditions',
  Setting: 'Setting',
  Order: 'Order',
  Favorite: 'Favorite',
  HeaderQuote: `Let's find your best look!`,
  Search: 'Search',
  Upcoming: 'Upcoming Designs',
};
