export default {
  Setting: 'Setting',
  EmailAddress: 'Email Address',
  Password: 'Password',
  LogIn: 'Log In',
  Account: `Don't have an account?`,
  Register: 'Register',
  ConfirmPassword: 'Confirm Password',
  HaveAccount: 'Already have an account?',
  LoginSuccessText: 'Login Successful!',
  RequestText: 'Please fill the input field!',
  RegisterSuccessfulText: 'Register Successful!',
  SamePasswordText: 'Password & Confirm password must be the same!',
  ErrorText: 'Email or Password incorrect!',
  LogOut: 'Log out',
  Home: 'Home',
  Profile: 'Profile',
  Terms: 'Terms & Conditions',
  Setting: 'Setting',
  Cart: 'Cart',
  Order: 'Order',
  Favorite: 'Favorite',
  HeaderQuote: `Let's find your best look!`,
  Search: 'Search',
  Upcoming: 'Upcoming Designs',
  AddCart: 'Add to Cart',
  Aggrement: 'AGGREMENTS TO TERMS',
  AggrementPara: `Welcome to Shop! H_M shopping Inc. and its Affiliates ("HM_shopping",“we”, “us”, or “our”) provide a mobile application and other productsand services that, among other things. By using Shop, you agree to bebound by these Terms of Service, and any new features or tools thatare added to the current Shop offering will also be subject to these Terms of Service.`,
  Shopping: `Shopping and Product Recommendations`,
  ShoppingPara: `1.11 Shop's product recommendations and shopping functionalities allow you to discover, browse, and purchase products from Shopify Merchants (“Products”). Shop may also make personalized recommendations to you based on Merchants you follow or your Saved Information. Notwithstanding any features or tools that we might make available in Shop, and unless otherwise explicitly stated, we do not endorse, and we are not affiliated with any Merchant or their Products.`,
  Representation: `Representations and warranties`,
  RepresentationPara: `By using Shop you represent and warrant that (i) you are at least 18 years of age, (ii) the information you provide in using Shop is true, accurate, and complete, and will not violate any applicable laws, regulations or rights of third parties, (iii) you will not use Shop for any fraudulent, unlawful or abusive purpose, and (iv) your use of Shop is not in violation of any obligation imposed on you.`,
  Governing: `Governing law`,
  GoverningPara: `These Terms of Service will be governed by and interpreted in accordance with the laws of the Province of Ontario, without regard to principles of conflicts of laws. You and we irrevocably and unconditionally submit to the exclusive jurisdiction of the provincial and federal courts of Ontario with respect to any dispute or claim arising out of or in connection with these Terms of Service or your use of Shop.`,
  Assignment: `Assignment`,
  AssignmentPara: `You may not assign these Terms of Service or any rights or obligations hereunder, by operation of law or otherwise, without our prior written approval and any such attempted assignment will be void. We reserve the right to freely assign these Terms of Service and the rights and obligations hereunder, to any third party without notice or consent. Subject to the foregoing, these Terms of Service will be binding upon and inure to the benefit of the parties hereto, their successors and permitted assigns.`,
  Severability: `Severability`,
  ServerPara: `In the event that any provision of these Terms of Service is determined by a court of competent jurisdiction to be unlawful, void or unenforceable, such provision will nonetheless be enforceable to the fullest extent permitted by applicable law, the unenforceable portion will be deemed to be severed from these Terms of Service, and such determination will not affect the validity and enforceability of any other remaining provisions.`,
  Survival: `Survival`,
  SurvivalPara: `Upon termination of your use of Shop or termination of these Terms of Service for any reason, the following sections will survive termination: Preamble, Sections 1.6, 2, 3.6 and 4 through 12. If you have any questions about Shop or these Terms of Service, please visit www.HM_shopping.app or contact us at help@HM_shopping.app.`,
  EmptyCart: 'Empty Cart',
  MyCart: 'My CartList',
  SuccessAdd: 'Successfully Added',
  LogOutSuccess: 'Log out Successful!',
  language: 'Language',
};
